name: Setup Git user
description: Sets the git user and email from a token
author: Federico Brigante + Trev
branding:
  icon: chevron-up
  color: yellow

inputs:
  app-id:
    description: app/client id
    required: true
  private-key:
    description: private key
    required: true

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: Get GitHub User ID
      shell: bash
      id: get-user-id
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

