name: Setup Git user
description: Sets the git user and email from a token
author: Federico Brigante + Trev
branding:
  icon: chevron-up
  color: yellow

inputs:
  token:
    description: "PAT or GitHub App Token"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        user=$(gh api user)
        echo $user

    - shell: bash
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
